### ISSUE TITLE
Latest version only returns first callback value if argumentNames is not set

### ISSUE THREAD

**Issue by bschlenk** [digitaldesignlabs/es6-promisify#39]
If argument names isn't set, then only the first value of the callback is resolved in the promise. Wouldn't it make more sense to resolve to an array of those callback values if there are more than one, instead of throwing the other ones away?

**Comment by mikehall314** [comment]
This is intentional, to match the behaviour of `util.promisify`.  Though `util.promisify` does allow you to supply a custom promisifier function, which this lib does not.  I never really saw the point, as it's trivial to write one with `new Promise((resolve, reject) => ...);` but perhaps the custom promisifier, which you could write to handle multiple arguments to the call back, would be a good feature to add.

**Comment by bschlenk** [comment]
Gotcha, didn’t realize the built in promisify did that. Maybe better asked in a new issue, what are this project’s goals compared with [utils.promisify](https://github.com/ljharb/util.promisify), which aims to be a direct polyfill for utils.promisify?
